package:
    name: libmetgem
    version: {{ GIT_DESCRIBE_TAG | replace("v", "") }}

source:
    path: ../

build:
    number: 0
    script: python -m pip install . -vv

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - python
        - cython
        - numpy>=1.19
        - scipy
        - versioneer
    run:
        - python
        - {{ pin_compatible('numpy') }}

test:
    imports:
        - libmetgem

about:
    home: http://github.com/metgem/libmetgem
    license: GPLv3
    license_family: GPL
    license_file: 'LICENSE'
    summary: 'A library for molecular networking based on MS/MS spectra. '
    description: 'A library for molecular networking based on MS/MS spectra.'
    doc_url: ''
    dev_url: 'http://github.com/metgem/libmetgem'

extra:
    recipe-maintainers: 'nicolas.elie@cnrs.fr'
